const mongoose = require("mongoose");

const orderSchema = mongoose.Schema({
    shippingInfo:[{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        pincode:{
            type:Number,
            required:true
        },
    }],
    orderItems:[{
        name:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
        quantity:{
            type:Number,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        product:{
            type:mongoose.Schema.ObjectId,
            ref:"product",
            required:true
        }
    }],
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"user",
        required:true
    },
    paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        },
    },
    paidAt:{
        type:Date,
        required:true
    },
    itemPrice:{
        type:Number,
        required:true
    },
    shippingPrice:{
        type:Number,
        required:true
    },
    totalPrice:{
        type:Number,
        required:true
    },
    taxPrice:{
        type:Number,
        required:true
    },
    orderStatus:{
        type:String,
        required:true,
        default:"Processing"
    },
    deliveredAt:Date,
   createdAt:{
       type:Date,
       default:Date.now
   }
})

module.exports = mongoose.model("order",orderSchema)